# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='viewCount',
            field=models.IntegerField(auto_created=0, default=0, verbose_name='\u6d4f\u89c8\u6b21\u6570'),
        ),
    ]
